// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kugoonmszogwjxwulhtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z29vbm1zem9nd2p4d3VsaHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODAwMzksImV4cCI6MjA3MTg1NjAzOX0.an8x2hzTQ1PKkKZpBXSDT8nEjBWsgR9_5K9BV_n5z_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});